<a href="https://colab.research.google.com/github/soohyunme/TensorFlow_Tutorial/blob/main/Code/01_Tensor_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '0'
import tensorflow as tf


# Initialization of Tensors

In [2]:
x = tf.constant(4,shape=(1,1),dtype=tf.float32)
print(x)

tf.Tensor([[4.]], shape=(1, 1), dtype=float32)


In [3]:
x = tf.constant([[1,2,3],[4,5,6]])
print(x)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [4]:
x = tf.ones((3,3))
print(x)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)


In [5]:
x = tf.zeros((2,3))
print(x)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)


In [6]:
x = tf.eye(3) # I fro the identity matrix (eye)
print(x)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [7]:
x = tf.random.normal((3,3),mean=0, stddev=1)
print(x)

tf.Tensor(
[[-0.31704867  0.10977877  0.16850117]
 [-0.16838664 -0.65591675  2.0661366 ]
 [ 0.6375513   0.6592904  -0.58581185]], shape=(3, 3), dtype=float32)


In [8]:
x = tf.random.uniform((1,3),minval=0, maxval=1)
print(x)

tf.Tensor([[0.5151925  0.27913105 0.44774127]], shape=(1, 3), dtype=float32)


In [9]:
x = tf.range(start=1,limit=10,delta=2)
print(x)

tf.Tensor([1 3 5 7 9], shape=(5,), dtype=int32)


In [10]:
x = tf.cast(x, dtype=tf.float64)
print(x)

tf.Tensor([1. 3. 5. 7. 9.], shape=(5,), dtype=float64)


# Mathematical Operations

In [11]:
x = tf.constant([1,2,3])
y = tf.constant([9,8,7])
print(x, y)

tf.Tensor([1 2 3], shape=(3,), dtype=int32) tf.Tensor([9 8 7], shape=(3,), dtype=int32)


In [12]:
z = tf.add(x,y)
print(z)

tf.Tensor([10 10 10], shape=(3,), dtype=int32)


In [13]:
z = x + y
print(z)

tf.Tensor([10 10 10], shape=(3,), dtype=int32)


In [14]:
z = tf.subtract(x, y)
print(z)

tf.Tensor([-8 -6 -4], shape=(3,), dtype=int32)


In [15]:
z = x - y
print(z)

tf.Tensor([-8 -6 -4], shape=(3,), dtype=int32)


In [16]:
z = tf.divide(x, y)
print(z)

tf.Tensor([0.11111111 0.25       0.42857143], shape=(3,), dtype=float64)


In [17]:
z = x / y
print(z)

tf.Tensor([0.11111111 0.25       0.42857143], shape=(3,), dtype=float64)


In [18]:
z = tf.multiply(x, y)
print(z)

tf.Tensor([ 9 16 21], shape=(3,), dtype=int32)


In [19]:
z = x * y
print(z)

tf.Tensor([ 9 16 21], shape=(3,), dtype=int32)


In [20]:
z = tf.tensordot(x, y, axes=1)
print(z)

tf.Tensor(46, shape=(), dtype=int32)


In [21]:
z = tf.reduce_sum(x*y, axis=0)
print(z)

tf.Tensor(46, shape=(), dtype=int32)


In [22]:
z = x ** 5
print(z)

tf.Tensor([  1  32 243], shape=(3,), dtype=int32)


In [23]:
x = tf.random.normal((2, 3))
y = tf.random.normal((3, 4))

In [24]:
z = tf.matmul(x, y)
print(z)

tf.Tensor(
[[-0.19271609  0.8193675  -0.39094955  0.5788662 ]
 [ 2.0861554   1.0293266  -0.7726362   2.8104942 ]], shape=(2, 4), dtype=float32)


In [25]:
z = x @ y
print(z)

tf.Tensor(
[[-0.19271609  0.8193675  -0.39094955  0.5788662 ]
 [ 2.0861554   1.0293266  -0.7726362   2.8104942 ]], shape=(2, 4), dtype=float32)


# Indexing

In [26]:
x = tf.constant([0, 1, 1, 2, 3, 1, 2, 3])
print(x[:])

tf.Tensor([0 1 1 2 3 1 2 3], shape=(8,), dtype=int32)


In [27]:
print(x[1:])

tf.Tensor([1 1 2 3 1 2 3], shape=(7,), dtype=int32)


In [28]:
print(x[1:3])

tf.Tensor([1 1], shape=(2,), dtype=int32)


In [29]:
print(x[::2])

tf.Tensor([0 1 3 2], shape=(4,), dtype=int32)


In [30]:
print(x[::-1])

tf.Tensor([3 2 1 3 2 1 1 0], shape=(8,), dtype=int32)


In [31]:
# x = tf.Tensor([0 1 1 2 3 1 2 3])
indices = tf.constant([0, 3])
x_ind = tf.gather(x, indices)
print(x_ind)

tf.Tensor([0 2], shape=(2,), dtype=int32)


In [32]:
x = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])
print(x[0,:])

tf.Tensor([1 2], shape=(2,), dtype=int32)


In [33]:
x = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])
print(x[0:2,:])

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


# Reshaping

In [34]:
x = tf.range(9)
print(x)

tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)


In [35]:
x = tf.reshape(x, (3,3))
print(x)

tf.Tensor(
[[0 1 2]
 [3 4 5]
 [6 7 8]], shape=(3, 3), dtype=int32)


In [36]:
x = tf.transpose(x, perm=[1,0]) # swap the 
print(x)

tf.Tensor(
[[0 3 6]
 [1 4 7]
 [2 5 8]], shape=(3, 3), dtype=int32)
